//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalDBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTAL
    {
        public int movie_number { get; set; }
        public int member_number { get; set; }
        public System.DateTime media_checkout { get; set; }
        public Nullable<System.DateTime> media_return_date { get; set; }
    }
}
